(async function(){
'use strict';
const D=ContourData,C=ContourConfig,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const fmt=v=>v===null||v===undefined?'—':new Intl.NumberFormat('uk-UA',{maximumFractionDigits:2}).format(v);
const shortDate=d=>d?d.slice(8)+'.'+d.slice(5,7):'—';
const fullDate=d=>d?shortDate(d)+'.'+d.slice(0,4):'—';
const paths={grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',layers:'m12 3 10 5-10 5L2 8z M2 12l10 5 10-5 M2 16l10 5 10-5',activity:'M2 12h4l3-8 6 16 3-8h4',upload:'M12 16V3 m-5 5 5-5 5 5 M4 15v6h16v-6',download:'M12 3v13 m-5-5 5 5 5-5 M4 16v5h16v-5',calendar:'M4 5h16v16H4z M8 3v4 M16 3v4 M4 10h16',database:'M4 6c0-4 16-4 16 0s-16 4-16 0 M4 6v12c0 4 16 4 16 0V6 M4 12c0 4 16 4 16 0',sliders:'M3 6h18 M3 12h18 M3 18h18 M8 3v6 M16 9v6 M10 15v6',trend:'M3 17l6-6 4 3 8-10 M15 4h6v6',bars:'M4 20V12h3v8 M11 20V4h3v16 M18 20V8h3v12',donut:'M12 3v9h9 M9 3.5a9 9 0 1 0 11.5 11.5 M15 3.5a9 9 0 0 1 5.5 5.5'};
const icon=n=>`<svg class="icon" aria-hidden="true" viewBox="0 0 24 24"><path d="${paths[n]||paths.grid}"/></svg>`;
$$('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
let data,sections,section,category,from,to,chartType='area',charts=[],current,tableRows=[],source=C.source(C.APP_CONFIG.sourceKinds.BUNDLED,C.APP_CONFIG.defaultWorkbook),generation=0;
let distributionIndex=0,graphMode='dynamics',detailChart=null,detailObserver=null;
const droneModes={};let suppressRailClick=false,categorySizeLock=null,returningToTop=false;
const splitCategory=c=>['assault','ongoing','territory','losses','positions','drones'].includes(c.id)&&c.fields.length>1;
$('#analysis-grid').insertAdjacentHTML('beforebegin','<div id="drone-anchor"></div><section id="drone-types" class="panel drone-types" aria-label="Типи БпС противника" hidden></section>');
$('#distribution-subtitle').insertAdjacentHTML('afterend','<div id="distribution-controls" class="distribution-controls"></div>');
const groupNames=[...C.GROUP_NAMES];
const groupLabel=n=>n.replace('УВ (с) ','').replaceAll('"','');
const palette=[D.colors.gold,D.colors.blue,D.colors.red,D.colors.green,D.colors.violet,D.colors.cyan,'#8e9ba1'];
function notify(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#toast').classList.remove('show'),3200)}
function empty(el,text='Немає даних за цей період',note='Змініть період або завантажте іншу книгу.'){el.innerHTML=`<div class="empty">${esc(text)}<small>${esc(note)}</small></div>`}
function chartError(el,error){console.error(error);empty(el,'Не вдалося побудувати графік','Табличні дані залишаються доступними. Спробуйте змінити період або категорію.')}
function setRange(days=7){const dates=data.sheets[section.sheet].dates;to=dates.at(-1);from=days==='all'?dates[0]:D.shift(to,-Number(days)+1);$('#from').value=from;$('#to').value=to;$$('[data-days]').forEach(b=>b.classList.toggle('active',b.dataset.days===String(days)))}
function selectSection(id){distributionIndex=0;section=sections.find(s=>s.id===id)||sections[0];category=section.categories[0];setRange(7);render()}
function selectCategory(id){
 categorySizeLock=document.body.classList.contains('cards-away');returningToTop=scrollY>0;
 distributionIndex=0;graphMode=id==='territory'?'balance':'dynamics';const wasOpen=$('#navigation-dialog').open;category=section.categories.find(c=>c.id===id)||section.categories[0];if(category.id==='drones')category=droneCategory({id:'other'});
 if(wasOpen)$('#navigation-dialog').close();render();followCategory();window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});dockScroll();
}
function navigation(){
$('#sections').innerHTML=sections.map(s=>`<button class="section-button ${s.id===section.id?'active':''}" data-section="${s.id}" aria-current="${s.id===section.id?'page':'false'}">${icon(s.icon)}<span>${esc(s.name)}</span></button>`).join('');
$('#sheet-sections').innerHTML=sections.map(s=>`<button data-section="${s.id}" class="${s.id===section.id?'active':''}" aria-pressed="${s.id===section.id}">${esc(s.short)}</button>`).join('');
const cats=section.categories.map((c,i)=>`<button class="category-button ${c.id===category.id?'active':''}" data-category="${c.id}" aria-pressed="${c.id===category.id}"><span class="cat-index">${String(i+1).padStart(2,'0')}</span><span>${esc(c.name)}</span>${c.id===category.id?'<span class="cat-arrow">↗</span>':''}</button>`).join('');
$('#inline-sections').innerHTML=sections.map(s=>`<button data-section="${s.id}" aria-pressed="${s.id===section.id}">${icon(s.icon)}${esc(s.short)}</button>`).join('');$('#categories').innerHTML=cats;$('#sheet-categories').innerHTML=cats;$('#category-count').textContent=String(section.categories.length).padStart(2,'0');
$$('[data-section]').forEach(b=>b.onclick=()=>selectSection(b.dataset.section));$$('[data-category]').forEach(b=>b.onclick=()=>selectCategory(b.dataset.category));
}
function spark(values,color){const finite=values.filter(v=>v!==null);if(!finite.length)return '<div class="spark"></div>';const lo=Math.min(...finite),hi=Math.max(...finite),pad=(hi-lo)*.15||Math.max(Math.abs(hi)*.05,1),min=lo-pad,max=hi+pad,h=27,w=180;let path='',gap=true;values.forEach((v,i)=>{if(v===null){gap=true;return}const x=i*w/Math.max(values.length-1,1),y=h-(v-min)/(max-min)*h+4;path+=`${gap?'M':'L'}${x.toFixed(1)},${y.toFixed(1)} `;gap=false});return `<svg class="spark" aria-hidden="true" viewBox="0 0 180 36" preserveAspectRatio="none"><path d="M0 34H180" stroke="${color}" opacity=".12"/><path d="${path}" fill="none" stroke="${color}" stroke-width="1.8" vector-effect="non-scaling-stroke"/>${from===to?`<line x1="${sparkX(values.length)}" x2="${sparkX(values.length)}" y1="0" y2="36" stroke="#c2bd51" stroke-dasharray="3 3"/>`:''}</svg>`}
function sparkX(length){const r=D.contextRange(data.sheets[section.sheet].dates,from,to);return Math.max(0,Math.min(180,(Date.parse(from)-Date.parse(r.from))/864e5*180/Math.max(length-1,1)))}
const signed=v=>v===null?'—':(v>0?'+':'')+fmt(v);
function percentNote(a,p,i){const c=D.change(a.totals[i],p.totals[i],a.complete&&p.complete);return c.percent===null?(c.delta===null?'Немає бази порівняння':'База попереднього періоду: 0'):signed(c.percent)+'% до попереднього періоду'}
function changeBadge(a,p,i){const c=D.change(a.totals[i],p.totals[i],a.complete&&p.complete),label=c.percent===null?(c.delta===null?'Немає порівняння':'База: 0'): `${c.percent>0?'↗':c.percent<0?'↘':'→'} ${c.percent>0?'+':''}${fmt(c.percent)}%`;return `<span class="change-badge" title="${esc(percentNote(a,p,i))}" aria-label="${esc(percentNote(a,p,i))}">${label}</span>`}
function metrics(){const row=$('#metrics'),previousScroll=row.scrollLeft;row.innerHTML=section.categories.map((c,i)=>{
 if(c.id==='drones')c={...c,fields:['FPV-дрони',C.WORKBOOK_SCHEMA.fields.ops.dronesOther],labels:['FPV','Інші БпС'],colors:['#e58caf',D.colors.gold]};
 const a=D.aggregate(data,section,c,from,to),range=D.contextRange(data.sheets[section.sheet].dates,from,to),plot=D.aggregate(data,section,c,range.from,range.to),prev=D.aggregate(data,section,c,D.shift(from,-a.days.length),D.shift(from,-1)),paired=splitCategory(c),indices=paired?[0,1]:[0];
 const balance=c.id==='territory'?(a.totals.every(v=>v!==null)?a.totals[0]-a.totals[1]:null):null;
 return `<button class="metric-card ${paired?'metric-card-paired ':''}${category.id===c.id?'active':''}" data-metric="${c.id}" aria-pressed="${category.id===c.id}"><span class="metric-top">${esc(c.name)}</span><div class="card-stats ${paired?'paired':''}">${indices.map(j=>`<div style="--series-color:${c.colors[j]}"><span class="stat-label">${paired||c.fields.length>1?esc(c.labels[j]):'За період'}</span><span class="stat-value"><strong>${fmt(a.totals[j])}</strong>${c.id!=='territory'?changeBadge(a,prev,j):''}</span></div>`).join('')}</div><div class="card-changes ${paired&&c.id!=='territory'?'paired':''}">${c.id==='territory'?`<span class="change-badge" title="Відновлено мінус втрачено">Δ ${signed(balance)} <small>баланс територій</small></span>`:''}</div><div class="card-sparks ${paired?'paired':''}" title="Динаміка · власний масштаб кожної серії">${indices.map(j=>spark(plot.series[j],c.colors[j])).join('')}</div>${a.present<a.days.length?`<span class="card-missing">${a.present?'Без даних: '+(a.days.length-a.present)+' із '+a.days.length+' днів':'Немає даних за період'}</span>`:''}</button>`;
 }).join('');row.scrollLeft=previousScroll;$$('[data-metric]').forEach(b=>b.onclick=()=>selectCategory(b.dataset.metric));updateRail();}
function updateRail(){const r=$('#metrics');r.classList.toggle('more-left',r.scrollLeft>3);r.classList.toggle('more-right',r.scrollLeft+r.clientWidth<r.scrollWidth-3);$('#rail-prev').disabled=r.scrollLeft<3;$('#rail-next').disabled=r.scrollLeft+r.clientWidth>=r.scrollWidth-3;}
function scrollRail(direction){const r=$('#metrics'),cards=[...r.children],edge=r.getBoundingClientRect().left;const target=direction>0?cards.find(c=>c.getBoundingClientRect().left>edge+12):cards.reverse().find(c=>c.getBoundingClientRect().left<edge-12);if(target)r.scrollBy({left:target.getBoundingClientRect().left-edge-4,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
$('#metrics').addEventListener('scroll',updateRail,{passive:true});$('#rail-prev').onclick=()=>scrollRail(-1);$('#rail-next').onclick=()=>scrollRail(1);$('#all-categories').onclick=()=>$('#navigation-dialog').showModal();
function followCategory(){const r=$('#metrics'),cards=[...r.children],i=cards.findIndex(c=>c.dataset.metric===category.id);if(i<0)return;const bounds=r.getBoundingClientRect(),box=cards[i].getBoundingClientRect();const ahead=cards.slice(i+1).filter(c=>c.getBoundingClientRect().right<=bounds.right).length;let dx=0;if(box.left<bounds.left)dx=box.left-bounds.left-4;else if(box.right>bounds.right||ahead<=2){const next=cards[Math.min(cards.length-1,i+3)];dx=box.right>bounds.right?box.right-bounds.right+4:Math.max(0,Math.min(next.getBoundingClientRect().right-bounds.right+4,box.left-bounds.left-4))}if(dx)r.scrollBy({left:dx,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}
function dragRail(rail){let drag=null;rail.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'||e.button!==0)return;drag={id:e.pointerId,x:e.clientX,left:rail.scrollLeft,moved:false};});rail.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x;if(Math.abs(dx)>6&&!drag.moved){drag.moved=true;rail.setPointerCapture(e.pointerId);rail.classList.add('is-dragging')}if(drag.moved){e.preventDefault();rail.scrollLeft=drag.left-dx}});const end=()=>{if(!drag)return;if(drag.moved){suppressRailClick=true;setTimeout(()=>{suppressRailClick=false},0)}rail.classList.remove('is-dragging');drag=null};rail.addEventListener('pointerleave',()=>{if(drag&&!drag.moved)drag=null});rail.addEventListener('pointerup',end);rail.addEventListener('pointercancel',end);rail.addEventListener('lostpointercapture',end);rail.addEventListener('click',e=>{if(suppressRailClick){e.preventDefault();e.stopImmediatePropagation()}},true);rail.addEventListener('dragstart',e=>e.preventDefault());}
dragRail($('#metrics'));
$('#metrics').addEventListener('transitionend',e=>{if(e.target===$('#metrics')&&e.propertyName==='height')updateRail()});
function droneCategory(type){const base=section.categories.find(c=>c.id==='drones');if(type?.id==='other')return {...base,name:'БпС без FPV',fields:[C.WORKBOOK_SCHEMA.fields.ops.dronesOther],labels:['Інші БпС (без FPV)'],colors:[D.colors.gold],droneType:'other'};return type?{...base,name:'БпС · '+type.name,fields:[type.field],labels:[type.name],colors:[type.color],droneType:type.id}:base}
function droneBreakdown(){return D.droneTypes.map(type=>({...type,value:D.aggregate(data,section,droneCategory(type),from,to).totals[0]}))}
function miniChart(values,color,mode,days){
 if(mode==='area')return spark(values,color);
 const limits=D.axisRange(values),width=220,height=48,y=v=>height-(v-limits.min)/(limits.max-limits.min)*height+4,zero=y(Math.max(limits.min,0)),step=width/Math.max(values.length,1);
 return `<svg viewBox="0 0 220 58" preserveAspectRatio="none" role="img" aria-label="Динаміка стовпчиками"><line x1="0" x2="220" y1="${zero}" y2="${zero}" stroke="#65716c" opacity=".4"/>${values.map((v,i)=>v===null?'':`<rect x="${i*step+step*.15}" y="${Math.min(y(v),zero)}" width="${Math.max(1,step*.7)}" height="${Math.max(1,Math.abs(y(v)-zero))}" rx="1" fill="${color}"><title>${fullDate(days[i])}: ${fmt(v)}</title></rect>`).join('')}${from===to?`<line x1="${(days.indexOf(from)+.5)*step}" x2="${(days.indexOf(from)+.5)*step}" y1="0" y2="58" stroke="#c2bd51" stroke-dasharray="3 3"/>`:''}</svg>`;
}
const modeLabel=m=>({area:'Лінійний графік',bar:'Стовпчиковий графік'}[m]);
function renderDroneTypes(){
 const panel=$('#drone-types'),previousScroll=panel.querySelector('.drone-type-grid')?.scrollLeft||0;
 panel.hidden=category.id!=='drones';$('#drone-anchor').hidden=panel.hidden;if(panel.hidden){panel.innerHTML='';panel.classList.remove('drone-compact');return}
 const rows=droneBreakdown(),all=D.aggregate(data,section,droneCategory(),from,to).totals[0],typed=D.sum(rows.map(r=>r.value)),difference=all!==null&&typed!==null?all-typed:null;
 const cards=[rows.find(r=>r.id==='fpv'),...rows.filter(r=>r.id!=='fpv')],cache=new Map();
 panel.innerHTML=`<div class="drone-heading"><div><h3>Типи БпС <span>· усього ${fmt(all)}</span></h3><p>FPV має окремий масштаб.</p></div><button id="drone-overview" class="text-button">Огляд без FPV</button></div><div class="drone-type-grid">${cards.map(r=>{
 const cat=droneCategory(r),a=D.aggregate(data,section,cat,from,to),prev=D.aggregate(data,section,cat,D.shift(from,-a.days.length),D.shift(from,-1)),range=D.contextRange(data.sheets[section.sheet].dates,from,to),plot=D.aggregate(data,section,cat,range.from,range.to),days=plot.days,raw=plot.series[0],mode=droneModes[r.id]||'area';cache.set(r.id,{r,days,raw});
 return `<article class="drone-type ${category.droneType===r.id?'active':''}" style="--type-color:${r.color}" data-drone-card="${r.id}"><button class="drone-select" data-drone="${r.id}" aria-pressed="${category.droneType===r.id}"><span class="drone-type-name">${esc(r.name)}</span><span class="drone-type-number"><span>${fmt(r.value)}</span>${changeBadge(a,prev,0)}</span></button><div class="drone-mini" title="Автомасштаб; вісь може не починатися з нуля">${miniChart(raw,r.color,mode,days)}</div><div class="drone-chart-modes" aria-label="Графік: ${esc(r.name)}">${['area','bar'].map(m=>`<button data-mini="${r.id}" data-mode="${m}" aria-label="${esc(r.name)}: ${modeLabel(m)}" aria-pressed="${mode===m}">${icon(m==='area'?'trend':'bars')}</button>`).join('')}</div></article>`;
 }).join('')}</div><p class="drone-source-note">Зміни % — до попереднього періоду. Автомасштаб; вісь може не починатися з нуля.${difference!==null&&Math.abs(difference)>.00001?' Сума типів не збігається із загальним підсумком.':difference===null?' Для звірки типів бракує даних.':''}</p>`;
 const grid=panel.querySelector('.drone-type-grid');if(grid)grid.scrollLeft=previousScroll;
 $$('[data-drone]').forEach(b=>b.onclick=()=>{category=droneCategory(b.dataset.drone==='other'?{id:'other'}:D.droneTypes.find(t=>t.id===b.dataset.drone));distributionIndex=0;render();$('[data-drone="'+b.dataset.drone+'"]').focus({preventScroll:true})});
 $$('[data-mini]').forEach(b=>b.onclick=()=>{const id=b.dataset.mini,mode=b.dataset.mode,item=cache.get(id),card=b.closest('.drone-type');droneModes[id]=mode;card.querySelector('.drone-mini').innerHTML=miniChart(item.raw,item.r.color,mode,item.days);card.querySelectorAll('[data-mini]').forEach(x=>x.setAttribute('aria-pressed',x===b));});
 $('#drone-overview').onclick=()=>{category=droneCategory({id:'other'});distributionIndex=0;render()};
}
function chartOptions(){return {chart:{fontFamily:'Exo,Arial,sans-serif',foreColor:'#8e9a9f',background:'transparent',toolbar:{show:false},animations:{enabled:!matchMedia('(prefers-reduced-motion: reduce)').matches,speed:450},parentHeightOffset:0},theme:{mode:'dark'},grid:{borderColor:'#343b3e',strokeDashArray:3,padding:{left:8,right:17}},tooltip:{theme:'dark'},dataLabels:{enabled:false},legend:{fontSize:'11px',position:'top',horizontalAlign:'left',markers:{size:4},itemMargin:{horizontal:9,vertical:4}},stroke:{width:2.2,curve:'straight'},noData:{text:'Немає даних'},states:{hover:{filter:{type:'lighten',value:.12}}}}}
function temporalOptions(a,labels,colors,height=260,balance=false,mode=chartType){
 const o=chartOptions(),single=from===to,t=Date.parse(from+'T12:00:00Z');
 let series=balance?[{name:'Відновлено − втрачено',data:a.days.map((d,j)=>({x:Date.parse(d+'T12:00:00Z'),y:a.series.every(s=>s[j]!==null)?a.series[0][j]-a.series[1][j]:null}))}]:labels.map((name,i)=>({name,data:a.days.map((d,j)=>({x:Date.parse(d+'T12:00:00Z'),y:a.series[i][j]}))}));
 const limits=D.integerAxis(series.flatMap(s=>s.data.map(p=>p.y)),balance);
 return {...o,chart:{...o.chart,type:mode,height},series,colors:balance?[D.colors.green]:colors,
 xaxis:{type:'datetime',labels:{datetimeUTC:true,formatter:(v,t)=>shortDate(new Date(t).toISOString().slice(0,10))},axisBorder:{show:false},axisTicks:{show:false},tooltip:{enabled:false}},
 yaxis:{...limits,forceNiceScale:false,labels:{formatter:v=>fmt(Math.round(v))}},
 fill:mode==='area'?{type:'gradient',gradient:{opacityFrom:.26,opacityTo:.02}}:{type:'solid',opacity:.9},
 plotOptions:{bar:{columnWidth:'48%',borderRadius:2,colors:{ranges:balance?[{from:-1e15,to:-.000001,color:D.colors.red},{from:0,to:1e15,color:D.colors.green}]:[]}}},markers:{size:a.days.length===1?4:0},
 annotations:{yaxis:balance?[{y:0,borderColor:'#9ba8aa',strokeDashArray:0}]:[],xaxis:single?[{x:t-432e5,x2:t+432e5,fillColor:D.colors.gold,opacity:.10,label:{offsetX:from>=a.days.at(-3)?-65:from<=a.days[2]?65:0,text:'Обрана доба · '+shortDate(from),style:{background:'#c2bd51',color:'#111315'},orientation:'horizontal'}},{x:t,borderColor:D.colors.gold,strokeDashArray:4}]:[]},
 tooltip:{theme:'dark',x:{formatter:t=>fullDate(new Date(t).toISOString().slice(0,10))},y:{formatter:v=>fmt(v)}}};
}
function plotData(group){const r=D.contextRange(data.sheets[section.sheet].dates,from,to);return D.aggregate(data,section,category,r.from,r.to,group)}
function trackChart(el,options){const epoch=generation,c=new ApexCharts(el,options);charts.push(c);return c.render().catch(error=>{if(epoch===generation)chartError(el,error);throw error})}
function detailRows(){
if(section.id==='ops'){const names=[...new Set(current.raw.map(r=>r.group))].filter(n=>n!==C.WORKBOOK_SCHEMA.rows.opsSummary);return names.map(name=>({name,values:category.fields.map((_,i)=>D.sum(current.raw.filter(r=>r.group===name).map(r=>D.values(r,category,section)[i]))),summary:groupNames.includes(name)}))}
if(section.id==='ovgp'){return [...new Set(current.rows.map(r=>r.name))].map(name=>({name,values:category.fields.map((_,i)=>D.sum(current.rows.filter(r=>r.name===name).map(r=>D.values(r,category,section)[i])))}))}
return current.days.map((date,j)=>({name:fullDate(date),date,values:current.series.map(s=>s[j])}));
}
function distribution(){
if(category.id==='drones'&&category.droneType==='other')return droneBreakdown().filter(r=>r.id!=='fpv').map(r=>({name:r.name,value:r.value,color:r.color}));
if(section.id==='personnel')return current.days.map((d,i)=>({name:shortDate(d),value:current.series[0][i],color:palette[i%palette.length]})).filter(r=>r.value!==null);
if(section.id==='compare')return category.labels.map((name,i)=>({name,value:current.totals[i],color:category.colors[i]}));
if(section.id==='ovgp')return groupNames.map((name,i)=>({name:groupLabel(name),value:D.sum(current.rows.map(r=>r.groups[name]?.[0]??null)),color:palette[i%palette.length]}));
return tableRows.filter(r=>r.summary).map((r,i)=>({name:groupLabel(r.name),value:r.values[distributionIndex],color:palette[i%palette.length]}));
}
function renderTable(){const cols=category.labels;const first=section.id==='ovgp'?'Засіб':['compare','personnel'].includes(section.id)?'Дата':'Угруповання';$('#details-title').textContent=section.id==='ovgp'?'Облік за засобами':['compare','personnel'].includes(section.id)?'Поденний облік':'Облік за угрупованнями';$('#details-subtitle').textContent=category.name+' · '+fullDate(from)+' — '+fullDate(to);
$('#table-head').innerHTML=`<tr><th>${first}</th>${cols.map((c,i)=>`<th style="color:${category.colors[i]}">${esc(c)}</th>`).join('')}<th>Профіль</th></tr>`;
const max=Math.max(...tableRows.map(r=>r.values[0]||0),1);
$('#table-body').innerHTML=tableRows.map((r,i)=>`<tr><td><button class="row-button" data-row="${i}" aria-label="Деталі: ${esc(r.name)}"><span class="row-index">${String(i+1).padStart(2,'0')}</span><span class="row-name">${esc(r.name)}</span></button></td>${r.values.map((v,j)=>`<td style="color:${category.colors[j]}">${fmt(v)}</td>`).join('')}<td><div class="table-bar" aria-hidden="true"><i style="width:${(r.values[0]||0)/max*100}%"></i></div></td></tr>`).join('')||`<tr><td colspan="${cols.length+2}">Немає записів за обраний період</td></tr>`;
$('#table-foot').textContent=section.id==='ops'?'Підсумкові угруповання та підпорядковані підрозділи показані окремо. Рядки не слід додавати між собою.':section.id==='ovgp'?'ВЗ — вогневі завдання. БП — боєприпаси. Підсумки взято зі стовпців «ВСЬОГО за СО».':'Пропуски позначені «—». Кожен рядок відповідає одній даті.';
$$('[data-row]').forEach(b=>b.onclick=()=>showDetail(tableRows[Number(b.dataset.row)]));}
function focus(){
if(splitCategory(category)){
const previous=D.aggregate(data,section,category,D.shift(from,-current.days.length),D.shift(from,-1));
$('#focus-content').innerHTML=category.labels.map((label,i)=>{const vals=current.series[i].filter(v=>v!==null),peak=vals.length?Math.max(...vals):null,day=peak===null?null:current.days[current.series[i].indexOf(peak)],delta=current.complete&&previous.complete&&current.totals[i]!==null&&previous.totals[i]!==null?current.totals[i]-previous.totals[i]:null;return `<div class="paired-focus" style="--series-color:${category.colors[i]}"><h4>${esc(label)}</h4><div class="context-row"><span>За період</span><strong>${fmt(current.totals[i])}</strong></div><div class="context-row"><span>Максимум за добу</span><strong>${fmt(peak)} <small>${fullDate(day)}</small></strong></div><div class="context-row"><span>Середнє за наявні дні</span><strong>${fmt(vals.length?D.sum(vals)/vals.length:null)}</strong></div>${category.id==='territory'?'':`<div class="context-row"><span>До попереднього періоду</span><strong>${percentNote(current,previous,i)}</strong></div>`}</div>`}).join('')+`<p class="focus-note">${category.id==='territory'?'Баланс: '+signed(current.totals.every(v=>v!==null)?current.totals[0]-current.totals[1]:null)+'. Відновлено мінус втрачено. Одиниця площі в заголовках джерела не вказана. ':''}${category.id==='territory'?'Додатний баланс — відновлено більше, ніж втрачено.':'Зміна порівнює повні періоди однакової тривалості.'}</p>`;return;
}
const vals=current.series[0].filter(v=>v!==null),max=vals.length?Math.max(...vals):null;const maxDate=max===null?null:current.days[current.series[0].indexOf(max)];const avg=vals.length?D.sum(vals)/vals.length:null;const previous=D.aggregate(data,section,category,D.shift(from,-current.days.length),D.shift(from,-1));const delta=current.complete&&previous.complete&&current.totals[0]!==null&&previous.totals[0]!==null?current.totals[0]-previous.totals[0]:null;
$('#focus-content').innerHTML=`<div class="focus-label">Максимум за добу · ${esc(category.labels[0])}</div><div class="focus-value">${fmt(max)}<small>${esc(category.unit)}</small></div><div class="focus-date">${fullDate(maxDate)}</div><div class="focus-rule"></div><div class="context-row"><span>Середнє за наявні дні</span><strong>${fmt(avg)}</strong></div><div class="context-row"><span>Зміна до попереднього періоду</span><strong>${delta!==null&&delta>0?'+':''}${fmt(delta)}</strong></div><div class="context-row"><span>Повнота періоду</span><strong>${current.present} / ${current.days.length} днів</strong></div><p class="focus-note">${delta===null?'Порівняння доступне, коли обидва періоди повністю забезпечені даними.':'Порівняння з попереднім періодом такої самої тривалості.'} ${category.id==='territory'?'Баланс: '+signed(current.totals.every(v=>v!==null)?current.totals[0]-current.totals[1]:null)+'. Відновлено мінус втрачено. Одиниця площі в заголовках джерела не вказана.':''}</p>`;
}
async function render(){if(!data||!category)return;const epoch=++generation;charts.forEach(c=>c.destroy());charts=[];navigation();metrics();current=D.aggregate(data,section,category,from,to);tableRows=detailRows();$('#page-title').innerHTML=esc(section.name)+'<span>.</span>';$('#section-code').textContent=String(sections.indexOf(section)+1).padStart(2,'0');$('#category-title').textContent=category.name;$('#page-subtitle').textContent=section.id==='ovgp'?'Вогневі завдання та боєприпаси за даними обліку':'Динаміка показників за обраний період';$('#period-note').textContent='Дані до '+fullDate(data.sheets[section.sheet].dates.at(-1));$('#coverage').hidden=current.complete;$('#coverage').textContent='Дані за '+current.present+' із '+current.days.length+' днів';$('.analysis-heading .eyebrow').textContent='Категорія '+(section.categories.findIndex(c=>c.id===category.id)+1)+' із '+section.categories.length;
let notice='';if(!current.present)notice='За обраний період немає даних. Оберіть інший діапазон дат.';else if(!current.complete)notice=`Неповний період: дані є за ${current.present} з ${current.days.length} днів. Підсумки враховують наявні записи.`;if(section.id==='ovgp'&&data.quality.find(q=>q.name==='ОВгП')?.errors)notice+=(notice?' ':'')+'У джерелі є помилки формул вартості. Вартість не включена до аналітики.';if(data.validation?.warnings?.length)notice+=(notice?' ':'')+`Перевірка структури книги: ${data.validation.warnings.length} попереджень. Деталі — «Про джерело».`;$('#notice').textContent=notice;$('#notice').hidden=!notice;
$('#chart-subtitle').textContent=fullDate(from)+' — '+fullDate(to)+' · '+category.unit;$('#chart-foot').innerHTML=category.labels.map((l,i)=>`<span><span style="color:${category.colors[i]}">●</span> ${esc(l)} <b>${fmt(current.totals[i])}</b></span>`).join('');renderTable();focus();renderDroneTypes();
$('#distribution-controls').innerHTML=splitCategory(category)?category.labels.map((label,i)=>`<button data-distribution="${i}" aria-pressed="${distributionIndex===i}" style="--series-color:${category.colors[i]}">${esc(label)}</button>`).join(''):'';
$$('[data-distribution]').forEach(b=>b.onclick=()=>{distributionIndex=Number(b.dataset.distribution);render();$('[data-distribution="'+distributionIndex+'"]').focus({preventScroll:true})});
$('#trend-chart').innerHTML='';$('#distribution-chart').innerHTML='';const tasks=[];
const plot=plotData(),balance=category.id==='territory'&&graphMode==='balance';
$('.trend-panel h3').textContent='Динаміка за період';
$('#chart-subtitle').textContent=fullDate(plot.days[0])+' — '+fullDate(plot.days.at(-1))+' · '+category.unit+' · Автомасштаб'+(!balance?' (вісь не обов’язково від 0)':'')+(from===to?' · контекст '+plot.days.length+' днів; обрану добу виділено':'');
let tabs=$('#graph-tabs');if(!tabs){$('.chart-controls').insertAdjacentHTML('afterbegin','<div id="graph-tabs" class="graph-tabs" role="group" aria-label="Категорія графіка"></div>');tabs=$('#graph-tabs')}
tabs.hidden=category.id!=='territory';tabs.innerHTML=['dynamics','balance'].map(m=>`<button data-graph="${m}" aria-pressed="${graphMode===m}">${m==='balance'?'Баланс · Δ':'Динаміка'}</button>`).join('');
$$('[data-graph]').forEach(b=>b.onclick=()=>{graphMode=b.dataset.graph;render()});$('.trend-panel .segmented').hidden=false;$$('[data-chart]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.chart===chartType)));
if(plot.present)tasks.push(trackChart($('#trend-chart'),temporalOptions(plot,category.labels,category.colors,260,balance)));else empty($('#trend-chart'));
if(category.id==='territory')$('#chart-foot').insertAdjacentHTML('beforeend',`<span class="balance-total">Баланс <b>${signed(current.totals.every(v=>v!==null)?current.totals[0]-current.totals[1]:null)}</b> · відновлено − втрачено</span>`);
const dist=distribution().filter(r=>r.value!==null&&r.value>=0).sort((a,b)=>b.value-a.value),total=D.sum(dist.map(r=>r.value)),max=Math.max(...dist.map(r=>r.value),1);
$('#distribution-subtitle').textContent=section.id==='compare'?'СОУ та противник':section.id==='personnel'?'Розподіл за днями':category.id==='drones'&&category.droneType==='other'?'Інші БпС · без FPV':category.labels[distributionIndex]+' · за угрупованнями';
$('#distribution-legend').innerHTML=dist.length?dist.map(r=>`<div class="distribution-item"><div><span>${esc(r.name)}</span><strong>${fmt(r.value)}</strong><small>${total?fmt(r.value/total*100)+'%':'0%'}</small></div><div class="distribution-track"><i style="--bar:${r.color};width:${r.value/max*100}%"></i></div></div>`).join(''):'<p class="focus-note">Немає даних для розподілу</p>';
if(section.id==='personnel'&&current.rows.length){const latest=[...current.rows].sort((a,b)=>a.date.localeCompare(b.date)).at(-1),key=category.fields[0].replace('_доба','');$('#focus-content').insertAdjacentHTML('beforeend',`<div class="focus-rule"></div><div class="focus-label">Станом на ${fullDate(latest.date)}</div><div class="context-row"><span>З початку року</span><strong>${fmt(D.number(latest[key+'_рік']))}</strong></div><div class="context-row"><span>Накопичений підсумок</span><strong>${fmt(D.number(latest[key+'_всього']))}</strong></div>`)}
await Promise.allSettled(tasks);if(epoch!==generation)return;dockScroll();
}
function showSource(){if(!data)return;const warnings=data.validation?.warnings||[];$('#source-content').innerHTML=`<p class="source-intro"><strong>${esc(source.name)}</strong><br>Тип джерела: ${source.kind===C.APP_CONFIG.sourceKinds.BUNDLED?'вбудована тестова книга':'імпортована користувачем книга'}. Книга опрацьовується у вашому браузері. Показники побудовані на збережених у файлі значеннях.</p>${warnings.map(w=>`<div class="source-card"><h3>Попередження структури · ${esc(w.sheet||'книга')}</h3><p class="warning">${esc(w.message)}</p></div>`).join('')}${data.quality.map(q=>`<div class="source-card"><h3>${esc(q.name)}</h3><p>${fmt(q.rows)} записів · ${fullDate(q.from)} — ${fullDate(q.to)}</p>${q.errors?`<p class="warning">${fmt(q.errors)} клітинок із помилками Excel.</p>`:''}${q.duplicates?`<p class="warning">${q.duplicates} повторів ключа. Перевірте первинні записи.</p>`:''}</div>`).join('')}<p class="source-method">Зведені показники ГОЧ беруться лише з рядків «${esc(C.WORKBOOK_SCHEMA.rows.opsSummary)}», щоб не дублювати підсумки угруповань. В ОВгП використовуються однойменні підсумкові стовпці. Нуль є значенням; пропуск або помилка позначаються «—». Накопичувальні колонки не підсумовуються за дні. Різні аркуші можуть мати різні останні дати. Зміна розділу відкриває його останні сім днів.</p><p class="source-method">Проведіть пальцем по заголовку детального огляду, щоб змінити категорію. Таблиці та картки прокручуються окремо.</p>`;$('#source-dialog').showModal()}
function mountDetailTrend(a,labels,colors,selected=null){
 let mode=chartType;const active=selected===null?null:new Set(selected);
 const host=$('#detail-trend-chart');host.insertAdjacentHTML('beforebegin',`<div class="detail-chart-controls" role="group" aria-label="Тип графіка деталізації">${['area','bar'].map(m=>`<button data-detail-mode="${m}" aria-label="${modeLabel(m)}" aria-pressed="${mode===m}">${icon(m==='area'?'trend':'bars')}</button>`).join('')}</div>${active?`<div class="detail-chart-legend" role="group" aria-label="Типи БпС на графіку">${labels.map((l,i)=>`<button data-detail-type="${i}" style="--type-color:${colors[i]}" aria-pressed="${active.has(i)}">${esc(l)}</button>`).join('')}</div><p id="detail-legend-hint" class="detail-drone-note"></p>`:''}`);
 const chartHeight=()=>{const summary=host.closest('.detail-summary'),values=summary?.querySelector('.detail-values'),trend=host.closest('.detail-trend');return values&&innerWidth>650?Math.max(280,Math.round(values.getBoundingClientRect().height-(host.getBoundingClientRect().top-trend.getBoundingClientRect().top))):320};
 const options=()=>{const indices=active?labels.map((_,i)=>i).filter(i=>active.has(i)):labels.map((_,i)=>i),visible={...a,series:indices.map(i=>a.series[i])},names=indices.map(i=>labels[i]),options=temporalOptions(visible,names,indices.map(i=>colors[i]),260,false,mode);
 if(active){options.legend={show:false};const split=active.has(0)&&indices.some(i=>i!==0),other=D.integerAxis(indices.filter(i=>i!==0).flatMap(i=>a.series[i])),fpv=D.integerAxis(a.series[0]),firstOther=indices.find(i=>i!==0);options.yaxis=indices.map(i=>({...((split&&i===0)?fpv:(split?other:D.integerAxis(visible.series.flat()))),seriesName:labels[i],show:split?(i===0||i===firstOther):i===indices[0],opposite:split&&i===0,forceNiceScale:false,title:{text:split?(i===0?'FPV':'Інші типи БпС'):''},labels:{formatter:v=>fmt(Math.round(v))}}));if(!indices.length)options.yaxis=[{show:false}];options.tooltip={...options.tooltip,shared:true,intersect:false};$('#detail-legend-hint').textContent=indices.length?'Увімкніть потрібні типи легендою. '+(split?'FPV — права вісь; інші типи — ліва.':'Вибрані типи мають спільну шкалу.'):'Оберіть хоча б один тип БпС у легенді.';}
 options.chart.height=chartHeight();options.chart.animations={enabled:false};return options};
 let chart=new ApexCharts(host,options());detailChart=chart;let pending=chart.render();
 const detailFailure=message=>{chartError(host,new Error(message));notify(message)};
 const refresh=()=>{pending=pending.then(()=>{if(detailChart!==chart||!$('#detail-dialog').open)return;chart.destroy();chart=new ApexCharts(host,options());detailChart=chart;return chart.render()}).catch(()=>detailFailure('Не вдалося оновити графік деталізації.'))};
 $$('[data-detail-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.detailMode;$$('[data-detail-mode]').forEach(x=>x.setAttribute('aria-pressed',x===b));refresh()});
 $$('[data-detail-type]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.detailType);active.has(i)?active.delete(i):active.add(i);b.setAttribute('aria-pressed',active.has(i));refresh()});
 pending=pending.catch(()=>detailFailure('Не вдалося відобразити графік деталізації.'));
 const values=host.closest('.detail-summary')?.querySelector('.detail-values');if(values){detailObserver?.disconnect();detailObserver=new ResizeObserver(()=>{pending=pending.then(()=>{if(detailChart===chart&&$('#detail-dialog').open)return chart.updateOptions({chart:{height:chartHeight()}},false,false)}).catch(()=>{});});detailObserver.observe(values)}
}
function showDroneDetail(row){
 const types=[D.droneTypes.find(t=>t.id==='fpv'),...D.droneTypes.filter(t=>t.id!=='fpv')],cat={...category,fields:types.map(t=>t.field),labels:types.map(t=>t.name),colors:types.map(t=>t.color)},a=D.aggregate(data,section,cat,from,to,row.name),range=D.contextRange(data.sheets[section.sheet].dates,from,to),plot=D.aggregate(data,section,cat,range.from,range.to,row.name);
 $('#detail-content').innerHTML=`<p class="source-intro">Типи БпС · ${fullDate(from)} — ${fullDate(to)}</p><div class="detail-summary detail-drone-summary"><div class="detail-values">${types.map((t,i)=>`<div><span>${esc(t.name)}</span><strong style="color:${t.color}">${fmt(a.totals[i])}</strong></div>`).join('')}</div><div class="detail-trend"><h3>Тенденція за типами БпС</h3><p>${fullDate(plot.days[0])} — ${fullDate(plot.days.at(-1))}${from===to?' · обрану добу виділено':''}</p><div id="detail-trend-chart"></div></div></div><div class="table-wrap detail-drone-table" tabindex="0" role="region" aria-label="Поденні дані за типами БпС"><table><thead><tr><th scope="col">Дата</th>${types.map(t=>`<th scope="col">${esc(t.name)}</th>`).join('')}</tr></thead><tbody>${a.days.map((d,j)=>`<tr><th scope="row">${fullDate(d)}</th>${a.series.map(series=>`<td>${fmt(series[j])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
 $('#detail-dialog').showModal();mountDetailTrend(plot,cat.labels,cat.colors,category.droneType&&category.droneType!=='other'?[types.findIndex(t=>t.id===category.droneType)]:types.map((_,i)=>i).filter(i=>i!==0));
}
function showDetail(row){if(detailChart){detailChart.destroy();detailChart=null;}$('#detail-name').textContent=row.name;if(section.id==='ops'&&category.id==='drones'){showDroneDetail(row);return}$('#detail-content').innerHTML=`<p class="source-intro">${esc(category.name)} · ${fullDate(from)} — ${fullDate(to)}</p><div class="detail-values">${category.labels.map((l,i)=>`<div><span>${esc(l)}</span><strong style="color:${category.colors[i]}">${fmt(row.values[i])}</strong></div>`).join('')}</div>`;
if(section.id==='ops'){const a=D.aggregate(data,section,category,from,to,row.name);$('#detail-content').innerHTML+=`<div class="table-wrap"><table><thead><tr><th>Дата</th>${category.labels.map(l=>`<th>${esc(l)}</th>`).join('')}</tr></thead><tbody>${a.days.map((d,j)=>`<tr><td>${fullDate(d)}</td>${a.series.map(s=>`<td>${fmt(s[j])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}else if(section.id==='ovgp'){const records=current.rows.filter(r=>r.name===row.name);$('#detail-content').innerHTML+=`<div class="table-wrap"><table><thead><tr><th>Дата</th><th>ВЗ</th><th>БП</th></tr></thead><tbody>${records.map(r=>`<tr><td>${fullDate(r.date)}</td>${D.values(r,category,section).map(v=>`<td>${fmt(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}$('#detail-dialog').showModal();if(section.id==='ops'){const a=plotData(row.name);$('.detail-values').insertAdjacentHTML('afterend','<div class="detail-trend"><h3>Тенденція</h3><p>'+fullDate(a.days[0])+' — '+fullDate(a.days.at(-1))+(from===to?' · обрану добу виділено':'')+'</p><div id="detail-trend-chart"></div></div>');const wrap=document.createElement('div');wrap.className='detail-summary';$('.detail-values').before(wrap);wrap.append($('.detail-values'),$('.detail-trend'));mountDetailTrend(a,category.labels,category.colors);}}
async function load(buffer,name,kind=C.APP_CONFIG.sourceKinds.USER){const parsed=D.parse(XLSX.read(buffer,{type:'array',cellDates:true,cellText:false}),XLSX);data=parsed;source=C.source(kind,name);sections=D.sections(data);section=sections[0];category=section.categories[0];const bundled=source.kind===C.APP_CONFIG.sourceKinds.BUNDLED,warnings=data.validation?.warnings?.length||0;$('#source-label').textContent=(bundled?'Тестова книга підключена':'Книгу підключено')+(warnings?' · є попередження':'');$('.demo-badge').textContent=bundled?'ТЕСТОВІ ДАНІ':'ІМПОРТОВАНІ ДАНІ';$('#footer-source').textContent='Джерело: '+source.name;setRange(7);await render();if(warnings)notify(`Книгу підключено з попередженнями: ${warnings}`)}
$('#import-button').onclick=()=>$('#file-input').click();$('#file-input').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>C.APP_CONFIG.maxImportBytes){notify(`Оберіть книгу розміром до ${Math.round(C.APP_CONFIG.maxImportBytes/1024/1024)} МБ.`);return}try{await load(await file.arrayBuffer(),file.name,C.APP_CONFIG.sourceKinds.USER);notify(data.validation?.warnings?.length?'Книгу підключено з попередженнями':'Книгу підключено')}catch(err){notify('Не вдалося прочитати книгу: '+err.message)}finally{e.target.value=''}};
$$('[data-days]').forEach(b=>b.onclick=()=>{if(!data)return;setRange(b.dataset.days);render()});
function updateDates(event){if(!data)return;let f=$('#from').value,t=$('#to').value;if(!f||!t)return;if(f>t){if(event.target.id==='from'){t=f;$('#to').value=t}else{f=t;$('#from').value=f}}const validation=D.validateDateRange(f,t);if(!validation.valid){notify(validation.reason);$('#from').value=from;$('#to').value=to;return}from=f;to=t;$$('[data-days]').forEach(b=>b.classList.remove('active'));render()}
$('#from').onchange=updateDates;$('#to').onchange=updateDates;
$$('[data-chart]').forEach(b=>b.onclick=()=>{chartType=b.dataset.chart;$$('[data-chart]').forEach(x=>x.classList.toggle('active',x===b));render()});
const step=n=>{if(!category)return;const c=section.categories;selectCategory(c[(c.findIndex(x=>x.id===category.id)+n+c.length)%c.length].id)};$('#previous').onclick=()=>step(-1);$('#next').onclick=()=>step(1);
const openNav=()=>{if(data)$('#navigation-dialog').showModal()};$('#mobile-categories').onclick=openNav;$('#mobile-menu').onclick=openNav;$('#source-button').onclick=showSource;$('#mobile-source').onclick=showSource;$('#mobile-overview').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});$('#mobile-dates').onclick=()=>{$('.filterbar').scrollIntoView({behavior:'smooth',block:'center'});$('#from').focus({preventScroll:true})};
$$('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
let touch;$('.analysis-heading').addEventListener('touchstart',e=>{touch=[e.touches[0].clientX,e.touches[0].clientY]},{passive:true});$('.analysis-heading').addEventListener('touchend',e=>{if(!touch)return;const dx=e.changedTouches[0].clientX-touch[0],dy=e.changedTouches[0].clientY-touch[1];if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.5)step(dx<0?1:-1);touch=null},{passive:true});
$('#export-button').onclick=()=>{if(!current?.present){notify('Немає даних для експорту.');return}const quote=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const rows=[['Категорія',category.name],['Період',from,to],['Назва',...category.labels],...tableRows.map(r=>[r.name,...r.values.map(v=>v===null?'':v)])];const blob=new Blob(['\ufeff'+rows.map(r=>r.map(quote).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Контур_${category.droneType||category.id}_${from}_${to}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('CSV підготовлено')};
$('#detail-dialog').addEventListener('close',()=>{detailObserver?.disconnect();detailObserver=null;detailChart?.destroy();detailChart=null});
let scrolling=false,droneFrame=0,droneProgress=0,droneTarget=0;
function arrangeDroneRow(panel,singleRow){
 if(panel.classList.contains('drone-row')===singleRow)return;
 const cards=[...panel.querySelectorAll('.drone-type')],oldHeight=panel.getBoundingClientRect().height,before=cards.map(el=>({box:el.getBoundingClientRect(),badge:el.querySelector('.change-badge').getBoundingClientRect()}));
 panel.getAnimations().forEach(a=>a.cancel());panel.classList.remove('drone-reflow');cards.forEach(el=>{el.getAnimations().forEach(a=>a.cancel());el.querySelector('.change-badge').getAnimations().forEach(a=>a.cancel())});panel.classList.toggle('drone-row',singleRow);
 if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;
 const timing={duration:460,easing:'cubic-bezier(.22,1,.36,1)'};
 const movement=panel.animate([{height:oldHeight+'px'},{height:panel.getBoundingClientRect().height+'px'}],timing);panel.classList.add('drone-reflow');movement.finished.catch(()=>{}).finally(()=>{if(!panel.getAnimations().length)panel.classList.remove('drone-reflow')});
 cards.forEach((el,i)=>{const box=el.getBoundingClientRect(),old=before[i].box,badge=el.querySelector('.change-badge'),next=badge.getBoundingClientRect(),prev=before[i].badge;el.animate([{transformOrigin:'top left',transform:`translate(${old.left-box.left}px,${old.top-box.top}px) scale(${old.width/box.width},${old.height/box.height})`},{transformOrigin:'top left',transform:'none'}],timing);badge.animate([{transform:`translate(${prev.left-next.left-(old.left-box.left)}px,${prev.top-next.top-(old.top-box.top)}px)`},{transform:'none'}],timing)});
}
function compressDrones(target){
 droneTarget=target;if(droneFrame)return;
 const tick=()=>{const panel=$('#drone-types'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;droneProgress=reduced?droneTarget:droneProgress+(droneTarget-droneProgress)*.18;if(Math.abs(droneTarget-droneProgress)<.001)droneProgress=droneTarget;panel.style.setProperty('--drone-collapse',droneProgress);panel.classList.toggle('drone-compact',droneProgress>=.995);arrangeDroneRow(panel,droneTarget>=.995&&droneProgress>=.98);panel.querySelectorAll('.drone-chart-modes').forEach(el=>el.inert=droneProgress>=.95);droneFrame=droneProgress===droneTarget?0:requestAnimationFrame(tick)};
 droneFrame=requestAnimationFrame(tick);
}
function dockScroll(){
 document.body.classList.toggle('is-scrolled',scrollY>70);
 const pinned=$('#dock-anchor').getBoundingClientRect().top<=$('.topbar').getBoundingClientRect().bottom+1;
 if(scrollY<=1)returningToTop=false;if(!returningToTop&&categorySizeLock===pinned)categorySizeLock=null;
 document.body.classList.toggle('cards-away',categorySizeLock??pinned);
 const dockBottom=$('#workspace-dock').getBoundingClientRect().bottom;document.documentElement.style.setProperty('--dock-bottom',dockBottom+'px');
 const panel=$('#drone-types');if(!panel.hidden){const distance=dockBottom+2-$('#drone-anchor').getBoundingClientRect().top;compressDrones(Math.max(0,Math.min(1,distance/180)))}
 scrolling=false;
}
addEventListener('scroll',()=>{if(!scrolling){scrolling=true;requestAnimationFrame(dockScroll)}},{passive:true});
addEventListener('scrollend',e=>{if(e.target===document){returningToTop=false;dockScroll()}});
addEventListener('wheel',()=>{returningToTop=false},{passive:true});
addEventListener('touchmove',()=>{returningToTop=false},{passive:true});
addEventListener('resize',()=>{dockScroll();updateRail()});new ResizeObserver(()=>dockScroll()).observe($('#workspace-dock'));dockScroll();

const clock=()=>$('#clock').textContent=new Intl.DateTimeFormat('uk-UA',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Kyiv'}).format(new Date());clock();setInterval(clock,30000);
try{const response=await fetch(encodeURI(C.APP_CONFIG.defaultWorkbook));if(!response.ok)throw new Error('Файл недоступний');await load(await response.arrayBuffer(),C.APP_CONFIG.defaultWorkbook,C.APP_CONFIG.sourceKinds.BUNDLED)}catch(e){$('#source-label').textContent='Книгу не підключено';empty($('#metrics'),'Підключіть книгу Excel',`Натисніть «Імпорт Excel» і виберіть «${C.APP_CONFIG.defaultWorkbook}».`);$('#notice').hidden=false;$('#notice').textContent='Автоматичне завантаження недоступне. Скористайтеся імпортом Excel.';console.error(e)}
})();
